config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    # root to: "bars#my_bars"
    root to: "pages#home"
  end

  unauthenticated :user do
    root to: 'pages#home'
  end

# BARS ROUTES
  # get "bars/:id", to: "bars#show"
  # get "bars/:id/edit", to: "bars#edit"
  # patch "bars/:id", to: "bars#update"
  # delete "bars/:id", to: "bars#destroy"

    # get "map", to: "bars#map"
    # get "local_bars", to: "bars#local_bars"


    #NEW ROUTE FOR BARS INDEX





  resources :bars, only: [ :show, :edit, :update, :delete ] do
    collection do
      get "my_bar/:id", to: "bars#my_bar", as: "my_bar"
      get "my_bars", to: "bars#my_bars"
      # get "local_bars", to: "bars#local_bars"
    end
    resources :menu_items
    resources :orders, only: [ :index, :new, :create]
    get "bars/:bar_id/orders/:id/make", to: "orders#make"
    get "bars/:bar_id/orders/:id/finish", to: "orders#finish"
  end

  resources :menu_items, only: [] do
    resources :basket_items
  end
  get '/basket_item/:id/remove', to: 'baskets#destroyredirect', as: "redirect"


  get '/basket', to: 'baskets#show'
  get "/checkout", to: 'baskets#checkout'

  resources :users, only: [] do
    get "/list/", to: 'orders#list', as: "list"
    resources :baskets
  end

  resources :orders, only: [:show, :update]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :basket_items
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  # def index
  #   @basket_items = current_user.basket_items
  #   @basket = policy_scope(Basket)
  # end

  def show
    @basket = Basket.find(current_user.basket.id) || Basket.create(user: current_user)
    if @basket.basket_items.any?
      @bar = @basket.basket_items.first.menu_item.bar

    end
    authorize @basket
  end

  def checkout
    @basket = Basket.find(current_user.basket.id)
    @bar = @basket.basket_items.first.menu_item.bar
    authorize @basket
  end

  def delete
    @basket = Basket.find(current_user.basket.id)
    @basket.destroy
    authorize @basket
  end
  # private

  # def basket_params
  #   params.require(:basket_item).permit()
  # end
end

app/views/baskets/checkout.html.erb
<div class= "container">

  <div class="box_basket">
    <div>
      <h1> Your Basket</h1>
      <h2>Items:</h2>
    </div>
        <div class="item_box">
          <% total= 0  %>
          <% @basket.basket_items.each  do |item|   %>
            <div>
              <div class="item_main">
                <%= item.quantity  %>X <%= item.menu_item.name %> £<%= item.menu_item.price  %>
              </div>
              <div>
              Sub-total: £<%=(item.quantity * item.menu_item.price).round(2) %>
              <% total += item.quantity * item.menu_item.price  %>
              </div>
            </div>
            <br>
          <% end %>
        </div>
        <div class="total_price">
          <h2>Total: <%= total.round(2) %></h2>
        </div>

        <div>
          <%= simple_form_for([@bar, Order.new]) do |f| %>
            <%= f.input :table_id, collection: @bar.tables %>
            <%= f.input :notes %>
            <%= f.submit %>
          <% end %>

        <div>
          <%= link_to "Back", bar_menu_items_path(@bar), class: "btn btn-primary"  %>
        </div>


        <div>
           <%= link_to "Order", bar_orders_path(@bar ), method: :post, class: "nav-link"  %>
        </div>
  </div>
</div>
<!-- params[:user_id][:notes][:creation_time][:completion_time] [:table_id] -->

app/views/baskets/new.js.erb
basket_item_field = document.getElementById('basket_item');
body = document.querySelector('.main');
basket_item_field.classList.remove("shrink");
body.classList.add("opaque");

if (basket_item_field.classList.contains("hidden")) {
 basket_item_field.classList.remove("hidden")
}



while (basket_item_field.firstChild) {
  basket_item_field.firstChild.remove()
}

insertBasketItem = (data) => {
    basket_item =
    `
  <h2> Selected Item: <%= @menu_item.name %></h2>
  <button class="btn"><i class="fas fa-times" id="exit_cross"></i></button>

  <div id="price" data-price="<%= @menu_item.price %>"><%= @menu_item.price%></div>

  <div class="actions">
    <a class="btn round-bordered incrementer"  id="btnMinus" data-offset="-1">-</a>
    <span id="counter" data-count="1">1</span>


    <a class="btn round-bordered incrementer" id= "btnPlus"  data-offset="1">+</a>
  </div>


  <%= simple_form_for([@menu_item, @basket_item], remote: true) do |f| %>
    <%= f.input :quantity, as: :hidden, input_html: { value: 1 } %>
    <button type='submit'>
      Add to basket
    </button>
    <% if current_user.basket %>
      <%= link_to "Basket", user_basket_path(current_user, current_user.basket.id), class: "nav-link"  %>

    <% else %>
    <% end %>

  <% end %>
`;
basket_item_field.insertAdjacentHTML('beforeend', basket_item);
};

insertBasketItem()

buttonPlus = document.getElementById("btnPlus");
buttonMinus = document.getElementById("btnMinus");
count_display = document.getElementById("counter");
counter = 1
price = document.getElementById("price").innerHTML;

plus = (data) => {
  buttonPlus.addEventListener("click", (event) => {
    event.preventDefault();
    counter += 1;
    document.getElementById('price').innerHTML = counter * parseFloat(price, 10);
    count_display.innerText = counter;
    price.value = price + (counter * price)
  });
};

minus = (data) => {
  buttonMinus.addEventListener("click", (event) => {
    event.preventDefault();
    counter -= 1;
    document.getElementById('price').innerHTML = counter * parseFloat(price, 10);
    count_display.innerText = counter

  });
};



plus()
minus()
setTimeout(function(){ basket_item_field.classList.add("shrink"); }, 500);
exit_div = document.getElementById('exit_cross');
exit = (data) => {
  exit_div.addEventListener("click", (event) => {
    event.preventDefault();
      body.classList.remove("opaque");
      basket_item_field.classList.add("hidden");
  });
};
exit()

app/views/baskets/show.html.erb
<div class="container">

  <div class= "order-container">

    <div class="box_basket">
      <div class="basket-header">
        <%= link_to bar_menu_items_path(current_user) do %>
          <i class="fas fa-arrow-left"></i>
        <% end %>
        Your Basket
        <%= link_to root_path do %>
          <i class="fas fa-home"></i>
        <% end %>
      </div>
      <% if @bar  %>

        <div class="mhresp-order-show">
          <div class="list-order">
            <% @basket.basket_items.each  do |item|   %>
            <%= link_to edit_menu_item_basket_item_path(@basket, item, item: item.id), remote: true do  %>
            <div class="totals" data-basket-item-id="<%= item.id %>">
              <%= item.quantity  %>x <%= item.menu_item.name %>
              <% total= 0  %>

              £<%=(item.quantity * item.menu_item.price).round(2) %>
              <% total += item.quantity * item.menu_item.price  %>



            </div>
            <% end %>
            <% end %>
          </div>
        </div>



        <div class="subtotal">
          <% total= 0  %>
          <% @basket.basket_items.each  do |item|   %>
          <%(item.quantity * item.menu_item.price) %>
          <% total += item.quantity * item.menu_item.price  %>
          <% end %>
          <div class="sub">
            Subtotal
            <div class="sub-tot">£<%= total.round(2) %></div>
          </div>
          <div class="service">
            Service fee
            <div class="fee">50p</div>
          </div>

        </div>


        <div class="order-footer">

          <div class="forms">
            <%= simple_form_for([@bar, Order.new]) do |f| %>

              <%= f.input :table_id, collection: [1,2,3,4,5,6,7,8,9,10,], label: 'Do you have a table number?'%>
              <%= f.input :notes, class: "til-input", label: 'Additional information' %>
              <li class="items-total">
                <span>Total:</span>
                <span>£<%= total.round(2) + 0.5 %></span>

              </li>
              <%= button_tag(type: 'submit', class: 'checkout-button' ) do %>
                <%= image_tag "applepay.png", alt: "apple pay", class: 'applepay' %>
              <% end %>
              <%#= f.submit "#{image_tag 'applepay.png' }", class: "order sw-button" %>
            <% end %>

            <div>

        </div>
          </div>



        </div>

      <% else %>
        <div class="empty_basket_div">
          <h3 class="empty_basket">Your Basket is Empty!</h3>
        </div>

      <% end %>
    </div>

  </div>
  <div class="basket_item_field stickycool stickycool-edit" id="basket_item"></div>
</div>

<!-- params[:user_id][:notes][:creation_time][:completion_time] [:table_id] -->