config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    # root to: "bars#my_bars"
    root to: "pages#home"
  end

  unauthenticated :user do
    root to: 'pages#home'
  end

# BARS ROUTES
  # get "bars/:id", to: "bars#show"
  # get "bars/:id/edit", to: "bars#edit"
  # patch "bars/:id", to: "bars#update"
  # delete "bars/:id", to: "bars#destroy"

    # get "map", to: "bars#map"
    # get "local_bars", to: "bars#local_bars"


    #NEW ROUTE FOR BARS INDEX





  resources :bars, only: [ :show, :edit, :update, :delete ] do
    collection do
      get "my_bar/:id", to: "bars#my_bar", as: "my_bar"
      get "my_bars", to: "bars#my_bars"
      # get "local_bars", to: "bars#local_bars"
    end
    resources :menu_items
    resources :orders, only: [ :index, :new, :create]
    get "bars/:bar_id/orders/:id/make", to: "orders#make"
    get "bars/:bar_id/orders/:id/finish", to: "orders#finish"
  end

  resources :menu_items, only: [] do
    resources :basket_items
  end
  get '/basket_item/:id/remove', to: 'baskets#destroyredirect', as: "redirect"


  get '/basket', to: 'baskets#show'
  get "/checkout", to: 'baskets#checkout'

  resources :users, only: [] do
    get "/list/", to: 'orders#list', as: "list"
    resources :baskets
  end

  resources :orders, only: [:show, :update]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :menu_item
  belongs_to :basket
end

app/controllers/basket_item_controller.rb
class BasketItemController < ApplicationController

  def new
    @basket_item = BasketItem.new
    authorize @basket_item
  end

  def create
    @basket_item = BasketItem.new(basket_item_params)
    if @basket_item.save
      # redirect_to new_basket_item_dose_path(@basket_item)
    else
      render :new
    end
    authorize @basket_item
  end

  def edit
    @basket_item = BasketItem.find(params[:id])
    authorize @basket_item
  end

  def update
    if @basket_item.update(basket_item_params)
      redirect_to basket_item_path(@basket_item)
    else
      render :edit
    end
    authorize @basket_item
  end

  def delete
    @basket_item = BasketItem.find(params[:id])
    @basket_item.destroy
    redirect_to root_path
    authorize @basket_item
  end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  def new
    @basket_item = BasketItem.new
    @menu_item = MenuItem.find(params[:menu_item_id])
    @basket = current_user.basket || Basket.create(user: current_user)
    if current_user.basket.basket_items.where(menu_item_id: @menu_item.id).present?
      @item_quantity = current_user.basket.basket_items.where(menu_item_id: @menu_item.id)[0].quantity
    else
      @item_quantity = 1
    end
    authorize @basket_item
    respond_to do |format|
      format.js
    end
  end

  def create
    @basket_item = BasketItem.find_or_initialize_by(menu_item_id: params[:menu_item_id].to_i)
    # @basket_item = BasketItem.new(basket_item_params)
    @basket_item.quantity = params.dig(:basket_item, :quantity).to_i
    @basket_item.menu_item_id = params[:menu_item_id]
    @basket = current_user.basket || Basket.create(user: current_user)
    @basket_item.basket = @basket

    if @basket_item.save!
      redirect_to bar_menu_items_path(MenuItem.where(id: params[:menu_item_id])[0].bar_id)
    else
      render :new
    end
    authorize @basket_item
  end

  def edit
    @basket_item = BasketItem.find(params[:id])
    @menu_item = MenuItem.find(@basket_item.menu_item.id)
    authorize @basket_item
    @item_quantity = current_user.basket.basket_items.where(menu_item_id: @menu_item)[0].quantity
    respond_to do |format|
      format.js

    end
  end

  def update
    @basket_item = BasketItem.find(params[:id])
    if @basket_item.update(basket_item_params)
      authorize @basket_item
      redirect_to basket_path
    else
      render :edit
    end
  end



  def destroy
    @basket_item = BasketItem.find(params[:id])
    @basket_item.destroy
    redirect_to basket_path
    # redirect_to root_path
    authorize @basket_item

  end


  private

  def basket_item_params
    params.require(:basket_item).permit(:quantity)
  end
end

app/views/basket_items/create.js.erb
basket_item_field = document.querySelector('.basket_item_field');
while (basket_item_field.firstChild) {
  console.log("hello")
  basket_item_field.firstChild.remove()
}
basket_item_field.insertAdjacentHTML('beforeend', '<div>Item added to basket</div>')
setTimeout(function(){ basket_item_field.firstChild.remove(); }, 500);
setTimeout(function(){ basket_item_field.classList.remove('shrink'); }, 500);
setTimeout(function(){ body.classList.remove("layer"); }, 500);

app/views/basket_items/edit.js.erb
basket_item_field = document.getElementById('basket_item');
body = document.querySelector('.opacitize');
basket_item_field.classList.remove("shrink");
// body.classList.add("layer");


<%#= item_quantity = current_user.basket.basket_items.find_by(menu_item_id: @menu_item)[0].quantity %>


if (basket_item_field.classList.contains("hidden")) {
  basket_item_field.classList.remove("hidden")
}

while (basket_item_field.firstChild) {
  basket_item_field.firstChild.remove()
}

insertBasketItem = (data) => {
    my_basket_item =
    `
    <div class="adding-item">
      <button class="back-menu"><i class="fas fa-times" id="exit_cross"></i></button>
      <div id="selected_item_name"> <%= @basket_item.menu_item.name %> </div>
      <div id="price" data-price="<%= @basket_item.menu_item.price %>">£<%= (@basket_item.menu_item.price * @basket_item.quantity).round(2) %></div>
    </div>


    <div class="actions">
      <a class="btn round-bordered incrementer"  id="btnMinus" data-offset="-1"><i class="fas fa-minus-circle"></i></a>
      <span id="counter" data-count="<%= @basket_item.quantity %>"><%= @basket_item.quantity %></span>



      <a class="btn round-bordered incrementer" id= "btnPlus"  data-offset="1"><i class="fas fa-plus-circle"></i></a>
    </div>



    <%= simple_form_for([@menu_item, @basket_item], input_html: {id: "form_value_quant"})  do |f| %>
      <%= f.input :quantity, as: :hidden, input_html: { value: @basket_item.quantity.to_i, id:"input_quant"} %>

      <button type='submit' id="quantbask">
        Update
      </button>

      <%= link_to menu_item_basket_item_path(),:method => "delete" do %>
          <button type='submit' id="destroy_item" class="hidden">
            Remove Item
          </button>
      <% end  %>



    <% end %>

`;
  basket_item_field.insertAdjacentHTML('beforeend', my_basket_item);
};
insertBasketItem()




buttonPlus = document.getElementById("btnPlus");
buttonMinus = document.getElementById("btnMinus");
count_display = document.getElementById("counter");
exit_div = document.getElementById('exit_cross');

// price = document.getElementById("price").innerHTML;
var price = document.getElementById("price").dataset.price;

counter = <%= current_user.basket.basket_items.where(menu_item_id: @menu_item)[0].quantity %>

plus = (data) => {
  buttonPlus.addEventListener("click", (event) => {
    event.preventDefault();
    counter += 1;
    console.log(document.getElementById('price'))
    let new_price = counter * parseFloat(price, 10);
    let n = `£ ${new_price.toFixed(2)} `;
    document.getElementById('price').innerHTML = n;
    console.log(counter * parseFloat(price, 10))
    count_display.innerText = counter;
    // price.value = price + (counter * price)
    // buttonPlus.classList.add('currently-loading')

  });
};

minus = (data) => {
  buttonMinus.addEventListener("click", (event) => {
    event.preventDefault();
    if (counter != 0) {
    counter -= 1;

    }


    let new_price = counter * parseFloat(price, 10);
    let n = `£ ${new_price.toFixed(2)} `;
    document.getElementById('price').innerHTML = n;
    count_display.innerText = counter

  });
};



plus()
minus()
setTimeout(function(){ basket_item_field.classList.add("shrink"); }, 500);


closeBox = (data) => {
  exit_div.addEventListener("click", (event) => {
    event.preventDefault();
      // body.classList.remove("layer");
      basket_item_field.classList.add("hidden");
  });
};
quantity = document.getElementById('counter');
bask = document.getElementById('quantbask');
destroy_item = document.getElementById('destroy_item');


input_quantity = document.getElementById("input_quant").value;

closeBox_added = (data) => {
  bask.addEventListener("click", (event) => {
// form_value_quant = document.getElementById("new_basket_item")
    event.preventDefault();

  form_value_quant = document.getElementById(event.currentTarget.parentElement.id)

      // give input a class
      // done
      // target the input
      // done
      // update the value with the counter
      document.getElementById("input_quant").value = counter;

      // submit the form
      basket_item_field.classList.remove("shrink");
      // body.classList.remove("layer");
      form_value_quant.submit();
  });
};
closeBox_added()

add_hidden = (data) => {
  buttonMinus.addEventListener("click", (event) => {
    event.preventDefault();
    if (count_display.innerHTML == 0) {
        bask.classList.add("hidden");
        destroy_item.classList.remove("hidden");

    };



  });
};

rem_hidden = (data) => {
  buttonPlus.addEventListener("click", (event) => {
    event.preventDefault();

        bask.classList.remove("hidden");
        destroy_item.classList.add("hidden")

  });
};



rem_hidden()
add_hidden()
closeBox()

app/views/basket_items/edit_one.js.erb
basket_item_field = document.querySelectorAll('.order_card');
// body = document.querySelector('.main');
// basket_item_field.classList.remove("shrink");
// body.classList.add("layer");

// if (basket_item_field.classList.contains("hidden")) {
//  basket_item_field.classList.remove("hidden")
// }



while (basket_item_field.firstChild) {
  basket_item_field.firstChild.remove()
}

insertBasketItem = (data) => {
    basket_item =
    `
  <div class="adding-item">

    <button class="back-menu"><i class="fas fa-times" id="exit_cross"></i></button>
    <div><%= @basket_item.menu_item.name %></div>
    <div id="price" data-price="<%= @basket_item.menu_item.price %>"><%= @basket_item.menu_item.price%></div>
  </div>


  <div class="actions">
    <a class="btn round-bordered incrementer"  id="btnMinus" data-offset="-1"><i class="fas fa-minus-circle"></i></a>
    <span id="counter" data-count="1">1</span>


    <a class="btn round-bordered incrementer" id= "btnPlus"  data-offset="1"><i class="fas fa-plus-circle"></i></a>
  </div>


  <%= simple_form_for([@basket_item.menu_item, @basket_item], remote: true) do |f| %>
    <%= f.input :quantity, as: :hidden, input_html: { value: 1 } %>

    <button type='submit', id="quantbask">
      Add to basket
    </button>
    <% if current_user.basket %>
      <%= link_to "Basket", user_basket_path(current_user, current_user.basket.id), class: "nav-link"  %>

    <% else %>
    <% end %>

  <% end %>
`;
  basket_item_field.insertAdjacentHTML('beforeend', basket_item);
      // body.classList.remove("layer");

};

insertBasketItem()

buttonPlus = document.getElementById("btnPlus");
buttonMinus = document.getElementById("btnMinus");
count_display = document.getElementById("counter");
counter = 1
price = document.getElementById("price").innerHTML;

plus = (data) => {
  buttonPlus.addEventListener("click", (event) => {
    event.preventDefault();
    counter += 1;
    document.getElementById('price').innerHTML = counter * parseFloat(price, 10);
    count_display.innerText = counter;
    price.value = price + (counter * price)
  });
};

minus = (data) => {
  buttonMinus.addEventListener("click", (event) => {
    event.preventDefault();
    while (counter != 0) {
    counter -= 1;
    }
    document.getElementById('price').innerHTML = counter * parseFloat(price, 10);
    count_display.innerText = counter

  });
};



plus()
minus()
setTimeout(function(){ basket_item_field.classList.add("shrink"); }, 500);


exit_div = document.getElementById('exit_cross');
exit = (data) => {
  exit_div.addEventListener("click", (event) => {
    event.preventDefault();
      body.classList.remove("layer");
      basket_item_field.classList.add("hidden");
  });
};
quantity = document.getElementById('counter');
bask = document.getElementById('quantbask');

add_hidden = (data) => {
  buttonMinus.addEventListener("click", (event) => {
    event.preventDefault();
    if (count_display.innerHTML == 0) {
        bask.classList.add("hidden");
    };
  });
};

add_hidden()

exit()

app/views/basket_items/new.js.erb
basket_item_field = document.getElementById('basket_item');
body = document.querySelector('.opacitize');
basket_item_field.classList.remove("shrink");
body.classList.add("layer");





if (basket_item_field.classList.contains("hidden")) {
 basket_item_field.classList.remove("hidden")
}



while (basket_item_field.firstChild) {
  basket_item_field.firstChild.remove()
}

insertBasketItem = () => {
    basket_item =
    `
    <div class="adding-item">
      <button class="back-menu"><i class="fas fa-times" id="exit_cross"></i></button>
     <div class="selected_item_menu"> <%= @menu_item.name %></div>
      <div id="price" data-price="<%= @menu_item.price %>">£<%= (@item_quantity * @menu_item.price).round(2) %></div>
    </div>


    <div class="actions">
      <a class="btn round-bordered incrementer"  id="btnMinus" data-offset="-1"><i class="fas fa-minus-circle"></i></a>
      <span id="counter" data-count="1"><%= @item_quantity %></span>



      <a class="btn round-bordered incrementer" id= "btnPlus"  data-offset="1"><i class="fas fa-plus-circle"></i></a>
    </div>



    <%= simple_form_for([@menu_item, @basket_item], input_html: {id:"form_value_quant"})  do |f| %>
      <%= f.input :quantity, as: :hidden, input_html: { value: @item_quantity, id:"input_quant"} %>

      <button type='submit', id="quantbask">
        Add to basket
      </button>


    <% end %>

`;
  basket_item_field.insertAdjacentHTML('beforeend', basket_item);
};
insertBasketItem()




buttonPlus = document.getElementById("btnPlus");
buttonMinus = document.getElementById("btnMinus");
count_display = document.getElementById("counter");
exit_div = document.getElementById('exit_cross');

var price = document.getElementById("price").dataset.price;

counter = <%= @item_quantity %>
console.log(counter);
plus = (data) => {
  buttonPlus.addEventListener("click", (event) => {
    event.preventDefault();
    counter += 1;
    console.log(document.getElementById('price'))
    let new_price = counter * parseFloat(price, 10);
    let n = `£ ${new_price.toFixed(2)} `;
    document.getElementById('price').innerHTML = n;
    console.log(counter * parseFloat(price, 10))
    count_display.innerText = counter;
    // price.value = price + (counter * price)
    // buttonPlus.classList.add('currently-loading')

  });
};

minus = (data) => {
  buttonMinus.addEventListener("click", (event) => {
    event.preventDefault();
    if (counter != 0) {
    counter -= 1;

    }

    let new_price = counter * parseFloat(price, 10);
    let n = `£ ${new_price.toFixed(2)} `;
    document.getElementById('price').innerHTML = n;
    count_display.innerText = counter

  });
};



plus()
minus()
setTimeout(function(){ basket_item_field.classList.add("shrink"); }, 500);


closeBox = (data) => {
  exit_div.addEventListener("click", (event) => {
    event.preventDefault();
      body.classList.remove("layer");
      basket_item_field.classList.add("hidden");
  });
};
quantity = document.getElementById('counter');
bask = document.getElementById('quantbask');


input_quantity = document.getElementById("input_quant").value;
form_value_quant = document.getElementById("new_basket_item")

closeBox_added = (data) => {
  bask.addEventListener("click", (event) => {

    event.preventDefault();

      // give input a class
      // done
      // target the input
      // done
      // update the value with the counter
      document.getElementById("input_quant").value = counter;

      // submit the form
      basket_item_field.classList.remove("shrink");
      body.classList.remove("layer");
      form_value_quant.submit();
  });
};
closeBox_added()

add_hidden = (data) => {
  buttonMinus.addEventListener("click", (event) => {
    event.preventDefault();
    if (count_display.innerHTML == 0) {
        bask.classList.add("hidden");
    };
  });
};
rem_hidden = (data) => {
  buttonPlus.addEventListener("click", (event) => {
    event.preventDefault();

        bask.classList.remove("hidden");
  });
};


add_hidden()
rem_hidden()
closeBox()