config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    # root to: "bars#my_bars"
    root to: "pages#home"
  end

  unauthenticated :user do
    root to: 'pages#home'
  end

# BARS ROUTES
  # get "bars/:id", to: "bars#show"
  # get "bars/:id/edit", to: "bars#edit"
  # patch "bars/:id", to: "bars#update"
  # delete "bars/:id", to: "bars#destroy"

    # get "map", to: "bars#map"
    # get "local_bars", to: "bars#local_bars"


    #NEW ROUTE FOR BARS INDEX





  resources :bars, only: [ :show, :edit, :update, :delete ] do
    collection do
      get "my_bar/:id", to: "bars#my_bar", as: "my_bar"
      get "my_bars", to: "bars#my_bars"
      # get "local_bars", to: "bars#local_bars"
    end
    resources :menu_items
    resources :orders, only: [ :index, :new, :create]
    get "bars/:bar_id/orders/:id/make", to: "orders#make"
    get "bars/:bar_id/orders/:id/finish", to: "orders#finish"
  end

  resources :menu_items, only: [] do
    resources :basket_items
  end
  get '/basket_item/:id/remove', to: 'baskets#destroyredirect', as: "redirect"


  get '/basket', to: 'baskets#show'
  get "/checkout", to: 'baskets#checkout'

  resources :users, only: [] do
    get "/list/", to: 'orders#list', as: "list"
    resources :baskets
  end

  resources :orders, only: [:show, :update]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :bar
  belongs_to :order_item, optional: true
  belongs_to :template_item, optional: true
  has_one_attached :drink_photo
end

app/controllers/menu_item_controller.rb
class MenuItemsController < ApplicationController

def index
    authorize @menu_item
    @menu_items = MenuItem.all
  end

  def show
    authorize @menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)
    if @menu_item.save
      # redirect_to new_menu_item_dose_path(@menu_item)
    else
      render :new
    end
  end

  def edit
    authorize @menu_item
    @menu_item = MenuItem.find(params[:id])
  end

  def update
    authorize @menu_item
    if @menu_item.update(menu_item_params)
      redirect_to menu_item_path(@menu_item)
    else
      render :edit
    end

  end

  def delete
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy
    redirect_to root_path
    authorize @menu_item
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :index, :show ]

def index
    @bar = Bar.find(params[:bar_id])
    @menu_items = policy_scope(MenuItem)
  end

  def show
    @menu_item = MenuItem.find(params[:id])
    authorize @menu_item
  end

  def new
    @bar = Bar.find(params[:bar_id])
    @menu_item = MenuItem.new
    authorize @menu_item
  end

  def create
    @bar = Bar.find(params[:bar_id])
    @menu_item = MenuItem.new(menu_item_params)
    @menu_item.bar = @bar

    if @menu_item.save
      redirect_to bar_menu_items_path(@bar)
    else
      render :new
    end
    authorize @menu_item
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
    authorize @menu_item
  end

  def update
    if @menu_item.update(menu_item_params)
      authorize @menu_item

      redirect_to menu_item_path(@menu_item)
    else
      render :edit
    end

  end

  def delete
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy
    redirect_to root_path
    authorize @menu_item
  end

  def menu_item_params
    params.require(:menu_item).permit(:name, :price, :description, :ingredients, :drink_photo)
  end
end

app/views/menu_items/_drink_card.html.erb
<%= link_to new_menu_item_basket_item_path(menuitem), class: "add_basket", remote: true do  %>
  <div class="card-product">
      <% if menuitem.drink_photo.attached? %>

          <%= cl_image_tag(menuitem.drink_photo.key,
           crop: :fit) %>
        <% else %>
          <%= cl_image_tag('barlycoa5vm',
          width: 200, height: 100, crop: :fill) %>
        <% end %>
      <div class="card-product-infos">
        <h2><%= menuitem.name %></h2>
        <p class="pull-left"><strong><%= menuitem.abv %></strong></p>
        <p><strong>£<%= menuitem.price %></strong></p>
      </div>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<div class="container">
  <h1>Edit product name:</h1>
  <%= simple_form_for @menu_item do |f| %>
    <%= f.input :name%>
    <%= f.input :price%>
    <%= f.input :description%>
    <%= f.input :ingredients  %>
    <%= f.input :bar_id, label: 'Bar' %>
    <br>
    <%= f.button :submit, class:"btn btn-primary"%>
  <% end %>
</div>


<!-- create_table "menu_items", force: :cascade do |t|
    t.string "name"
    t.float "price"
    t.text "description"
    t.string "ingredients"
    t.bigint "bar_id"
    t.bigint "template_item_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["bar_id"], name: "index_menu_items_on_bar_id"
    t.index ["template_item_id"], name: "index_menu_items_on_template_item_id"
  end -->

app/views/menu_items/index.html.erb
<div class="container">
  <div id="top-holder">
     <div class="bar-banner" style="background-image: url('<%= asset_path("bar_banner.jpg") %>'); background-repeat: no-repeat; background-size: cover; background-position: center;">
      <%= link_to root_path do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    </div>
      <div class="bar-details">
        <h3><%= @bar.name %></h3>
        <p><%= @bar.address %></p>
        <%= link_to "Admin Settings", my_bars_bars_path, class: "btn btn-outline-dark" if current_user.bars.include?(@bar) %>
      </div>
      <div class="drink-buttons-arthur" id="drinks-navbar">
        <span class="menu-category active" data-id="beer">Beer</span>
        <span class="menu-category" data-id="cocktail">Cocktails</span>
        <span class="menu-category" data-id="wine">Wine</span>

        <!-- <span class="menu-category" data-id="mocktail">Mocktails</span> -->
        <span class="last">
          <span class="menu-category" data-id="soft_drink">Soft Drinks</span>
        </span>
      </div>
      <div class="mhresp">
        <div class="opacitize">
          <% if @bar.menu_items.where(category: 'Beer').any? %>
            <div id="beer" class="menu-item-container">
              <h1>Beer</h1>
              <% @bar.menu_items.where(category: 'Beer').find_each do |menuitem| %>
                <%= render 'drink_card', menuitem: menuitem %>
              <% end %>
            </div>
          <% end %>

          <% if @bar.menu_items.where(category: 'Cocktail').any? %>
            <div id="cocktail" class="menu-item-container">
              <h1>Cocktails</h1>
              <% @bar.menu_items.where(category: 'Cocktail').find_each do |menuitem| %>
                <%= render 'drink_card', menuitem: menuitem %>
              <% end %>
            </div>
          <% end %>

          <% if @bar.menu_items.where(category: 'Wine').any? %>
            <div id="wine" class="menu-item-container">
              <h1>Wine</h1>
              <% @bar.menu_items.where(category: 'Wine').find_each do |menuitem| %>
                <%= render 'drink_card', menuitem: menuitem %>
              <% end %>
            </div>
          <% end %>



          <% if @bar.menu_items.where(category: 'Soft Drink').any? %>
            <div id="soft_drink" class="menu-item-container">
              <h1>Soft Drinks</h1>
              <% @bar.menu_items.where(category: 'Soft Drink').find_each do |menuitem| %>
                <%= render 'drink_card', menuitem: menuitem %>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="basket_item_field stickycool" id="basket_item">
        </div>
      </div>
    </div>
    <% if current_user&.basket&.basket_items&.any? %>
      <% total = 0 %>
      <% counter = 0 %>
      <% current_user.basket.basket_items.each do |item|%>
        <% counter += item.quantity %>
        <% total += (item.quantity * item.menu_item.price) %>
        <% current_user.basket.total_price %>
      <% end %>
      <%= link_to user_basket_path(current_user, current_user.basket), id:"basket_wrapper" do %>
        <div class="basket-styling">
          <div class="basket_text">
            <p class="basket-items"><strong><%= counter %></strong></p>
            <p class="view">View Basket</p>
            <p class="basket-total"><strong>£<%= total.round(2) %></strong></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= content_for(:after_js) do %>
  <%= javascript_pack_tag 'list_scroll' %>
<% end %>

app/views/menu_items/new.html.erb
<div class="container">

<%= simple_form_for [@bar, @menu_item], method: :post, url: bar_menu_items_path(@bar) do |f| %>
  <%= f.input :name %>
  <%= f.input :price %>
  <%= f.input :description%>
  <%= f.input :ingredients%>
  <%= f.input :drink_photo, as: :file%>


  <br>
  <%= f.button :submit, class: "signin_button" %>
<% end %>

</div>



<!-- create_table "menu_items", force: :cascade do |t|
    t.string "name"
    t.float "price"
    t.text "description"
    t.string "ingredients"
    t.bigint "bar_id"
    t.bigint "template_item_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["bar_id"], name: "index_menu_items_on_bar_id"
    t.index ["template_item_id"], name: "index_menu_items_on_template_item_id"
  end -->