config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    # root to: "bars#my_bars"
    root to: "pages#home"
  end

  unauthenticated :user do
    root to: 'pages#home'
  end

# BARS ROUTES
  # get "bars/:id", to: "bars#show"
  # get "bars/:id/edit", to: "bars#edit"
  # patch "bars/:id", to: "bars#update"
  # delete "bars/:id", to: "bars#destroy"

    # get "map", to: "bars#map"
    # get "local_bars", to: "bars#local_bars"


    #NEW ROUTE FOR BARS INDEX





  resources :bars, only: [ :show, :edit, :update, :delete ] do
    collection do
      get "my_bar/:id", to: "bars#my_bar", as: "my_bar"
      get "my_bars", to: "bars#my_bars"
      # get "local_bars", to: "bars#local_bars"
    end
    resources :menu_items
    resources :orders, only: [ :index, :new, :create]
    get "bars/:bar_id/orders/:id/make", to: "orders#make"
    get "bars/:bar_id/orders/:id/finish", to: "orders#finish"
  end

  resources :menu_items, only: [] do
    resources :basket_items
  end
  get '/basket_item/:id/remove', to: 'baskets#destroyredirect', as: "redirect"


  get '/basket', to: 'baskets#show'
  get "/checkout", to: 'baskets#checkout'

  resources :users, only: [] do
    get "/list/", to: 'orders#list', as: "list"
    resources :baskets
  end

  resources :orders, only: [:show, :update]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "Barly_dark.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
          <% if current_user.basket %>
            <%= link_to "Basket", user_basket_path(current_user, current_user.basket.id), class: "nav-link"  %>
            <%= link_to "My Orders", user_list_path(current_user), class: "dropdown-item" %>
          <% else %>
          <% end %>
        </li>
        <li class="nav-item">
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_sticky_basket_item.html.erb
<div >
  <h2> Selected Item:</h2>
  <%#= menu_item.price * quantity %>

  <div class="actions">
    <a class="btn round-bordered incrementer minus"  id="btnMinus" data-offset="-1">-</a>
    <span id="counter" data-count="1">1</span>
    <a href="#" id= "btnPlus" class="btn round-bordered incrementer" data-offset="1">+</a>
  </div>


  <button>
    Add to basket
  </button>



</div>